src/devices/device.ts
=> fix: Device: clean up old saved states

src/index.ts
=> chore: bump to rebuild and republish over pr

package.json, yarn.lock
Updated timeline library. It contains a big refactoring, so it SHOULD not have any noticeable impact.
=> feat: updated timeline dependency

package.json, src/__mocks__/hyperdeck-connection.ts, src/__tests__/hyperdeck.spec.ts, src/conductor.ts, src/devices/abstract.ts, src/devices/atem.ts, src/devices/casparCG.ts, src/devices/device.ts, src/devices/httpSend.ts, src/devices/hyperdeck.ts, src/devices/lawo.ts, src/devices/mapping.ts, src/devices/panasonicPTZ.ts, yarn.lock
* This PR adds the hyperdeck device. Currently only with support for recording
(This PR is a work-in-progress)
=> Feature/hyperdeck record (wip)

src/devices/casparCG.ts
=> fix(casparcg): device name

src/devices/casparCG.ts, src/types/src/casparcg.ts
feat: add casparcg-property noStarttime to avoid seeking in certain situations
=> Hotfix: add noStarttime

src/devices/__tests__/osc.spec.ts, src/devices/osc.ts, src/easings.ts, src/types/src/osc.ts
Allows one to tween values in the OSC device to dim lights or fade audio for example.
This is dependent on the timeline v2 branch.
=> Feature: osc tweens

src/devices/__tests__/quantel.spec.ts, src/devices/__tests__/quantelGateway.spec.ts, src/devices/__tests__/quantelGatewayMock.ts, src/devices/quantel.ts, src/devices/quantelGateway.ts, src/doOnTime.ts, src/types/src/quantel.ts
This PR fixes issues with Quantel playout
=> Quantel playout

src/devices/quantel.ts, src/devices/quantelGateway.ts
If, for some unknown reason, the quantel device doesn't start playing; retry a couple of times
=> Quantel: retry play if failed

package.json, src/__mocks__/hyperdeck-connection.ts, src/devices/device.ts, src/devices/hyperdeck.ts, yarn.lock
This PR introduces improved status notifications for the Hyperdeck devices. Notifications for missings disks as well stopped recordings are now enabled. Beyond that the TSR device will enforce remote access from the Hyperdeck.
=> Hyperdeck status notifications

package.json
Bug fix
There was a bug in `casparcg-state` that caused some nextUp changes to be ignored.
The bug was fixed in `casparcg-state` and this PR updates the dependency. 
=> chore: update deps for a bugfix in casparcg-state

package.json, src/__tests__/rundown.spec.ts, src/devices/__tests__/casparcg.spec.ts, src/devices/casparCG.ts, src/types/src/casparcg.ts, yarn.lock
Enables a developer to specifiy a filter and a format property for CasparCG Decklink inputs
=> Casparcg decklink format/filter

src/devices/quantelGateway.ts
After restarting the quantel gateway it is not connected to an ISA. The TSR has to recognise this situation and attempt to connect the gateway to an ISA.
Previously, the TSR would attempt to parse the response from the gateway and take measure if it contained the error. However, if the gateway is not connected an error will be thrown rather than a bad response and this meant the TSR would not check if that was related to a missing ISA.
This PR attempts to catch errors, check if they are ISA related and handle if they are.
=> fix(quantel): catch error on missing ISA after restart

src/devices/casparCG.ts
=> fix: default casparcg.retryInterval to disabled

package.json, src/__tests__/rundown.spec.ts, src/devices/__tests__/casparcg.spec.ts, src/devices/casparCG.ts, src/types/src/casparcg.ts, yarn.lock
This updates casparcg-state to v2. While v2 is a breaking change this should not have effect on TSR. Retries should work more reliably though due to improved timing calculations in ccg-state.
=> CasparCG state v2

package.json, src/__mocks__/_setup-all-mocks.ts, src/__mocks__/emberplus.ts, src/__tests__/conductor.spec.ts, src/conductor.ts, src/devices/__tests__/httpwatcher.spec.ts, src/devices/__tests__/hyperdeck.spec.ts, src/devices/__tests__/panasonicPTZ.spec.ts, src/devices/__tests__/panasonicPTZAPI.spec.ts, src/devices/__tests__/pharos.spec.ts, src/devices/__tests__/pharosAPI.spec.ts, src/devices/__tests__/sisyfos.spec.ts, src/devices/__tests__/sisyfosAPI.spec.ts, src/devices/__tests__/vizMSE.spec.ts, src/devices/deviceContainer.ts, src/devices/vizMSE.ts, src/types/src/lawo.ts, yarn.lock
Updates the threadedClass library to latest version, 0.8.0
TSR uses version 0.7.0
=> chore: update threaded class to version 0.8.0

packages/timeline-state-resolver/src/devices/atem.ts
Disables controlling Atem Auxes if they are not mapped in Sofie
Unmapped auxes will be set to black which can interfere with other devices controlling the aux for things like colour correction.
=> feat: disable control of unmapped atem auxes

packages/timeline-state-resolver/src/conductor.ts
Improve size calculation of the timeline, in order to get a better estimatedResolveTime.
Also emits the size, so that statistics can be collected for a better estimatedResolveTime calculation.
=> fix: Improve size calculation of the timeline,

package.json, packages/timeline-state-resolver/package.json, packages/timeline-state-resolver/src/AsyncResolver.ts, packages/timeline-state-resolver/src/conductor.ts, packages/timeline-state-resolver/src/doOnTime.ts, yarn.lock
This PR does a few minor fixes with the aim of increasing performance.
=> Fix: Optimizations

README.md
Fixes README.md Codecov broken badge
Badge is not loading, and is showing unknown status.
This fixes the old, broken badge.
Example:
[![codecov](https://codecov.io/gh/nrkno/sofie-timeline-state-resolver/branch/master/graph/badge.svg)](https://codecov.io/gh/nrkno/tv-automation-state-timeline-resolver)
=> fix: Fix broken Codecov

packages/timeline-state-resolver/src/devices/lawo.ts
Bug fix
Error "TypeError: Cannot read property 'contents' of undefined"
Error "Unable to setValue for node "${command.path}", node not found!"
=> fix: Lawo: Typings issue, getElementByPath can return undefined.

packages/timeline-state-resolver/src/devices/casparCG.ts
Update the connection status in core whenever a CasparCG AMCP queue has overflown.
Status will remain good in core even though no commands are accepted.
Untested as it's pretty hard to stimulate an overflow situation in CasparCG.
=> fix(casparcg): update status on queue overflow

packages/timeline-state-resolver-types/src/__tests__/__snapshots__/index.spec.ts.snap, packages/timeline-state-resolver-types/src/device.ts, packages/timeline-state-resolver-types/src/index.ts, packages/timeline-state-resolver-types/src/sofieChef.ts, packages/timeline-state-resolver/src/__mocks__/ws.ts, packages/timeline-state-resolver/src/__tests__/__snapshots__/index.spec.ts.snap, packages/timeline-state-resolver/src/conductor.ts, packages/timeline-state-resolver/src/integrations/sofieChef/__tests__/sofieChef.spec.ts, packages/timeline-state-resolver/src/integrations/sofieChef/api.ts, packages/timeline-state-resolver/src/integrations/sofieChef/index.ts
This PR adds a device for controlling the Sofie Chef software (https://github.com/nrkno/sofie-chef).
Left to do:
=> Feat: Sofie Chef Device

packages/timeline-state-resolver-types/src/__tests__/__snapshots__/index.spec.ts.snap, packages/timeline-state-resolver-types/src/device.ts, packages/timeline-state-resolver-types/src/index.ts, packages/timeline-state-resolver-types/src/multiOsc.ts, packages/timeline-state-resolver/src/__tests__/__snapshots__/index.spec.ts.snap, packages/timeline-state-resolver/src/conductor.ts, packages/timeline-state-resolver/src/integrations/multiOsc/__tests__/multiOsc.spec.ts, packages/timeline-state-resolver/src/integrations/multiOsc/deviceConnection.ts, packages/timeline-state-resolver/src/integrations/multiOsc/index.ts, packages/timeline-state-resolver/src/integrations/osc/index.ts
=> feat: multi osc

.github/workflows/prune-tags.yml
CI
No tag pruning
Tags are pruned on a schedule
=> ci: Prune repo tags

packages/quick-tsr/src/tsrHandler.ts
Bug fix
QuickTSR fails to compile due to TypeScript errors
QuickTSR compiles
=> fix: Update changed typings

packages/timeline-state-resolver/src/conductor.ts, packages/timeline-state-resolver/src/integrations/httpSend/index.ts, packages/timeline-state-resolver/src/integrations/osc/index.ts, packages/timeline-state-resolver/src/integrations/shotoku/__tests__/shotoku.spec.ts, packages/timeline-state-resolver/src/integrations/shotoku/index.ts, packages/timeline-state-resolver/src/service/devices.ts, packages/timeline-state-resolver/src/service/remoteDeviceInstance.ts
=> chore: refactor shotoku device

packages/timeline-state-resolver/src/service/__tests__/deviceInstance.spec.ts
This PR adds unit tests specific to the DeviceInstance class. Based off of https://github.com/nrkno/sofie-timeline-state-resolver/pull/276
=> Chore: unit test device instance

packages/timeline-state-resolver/src/__tests__/conductor.spec.ts, packages/timeline-state-resolver/src/conductor.ts, packages/timeline-state-resolver/src/integrations/httpSend/__tests__/httpsend.spec.ts, packages/timeline-state-resolver/src/integrations/httpSend/index.ts, packages/timeline-state-resolver/src/service/devices.ts
=> Backport http device to r50

packages/timeline-state-resolver/src/integrations/multiOsc/index.ts
=> chore: add more logging to multi-osc

packages/timeline-state-resolver/src/__mocks__/emberplus-connection.ts, packages/timeline-state-resolver/src/conductor.ts, packages/timeline-state-resolver/src/integrations/lawo/__tests__/lawo.spec.ts, packages/timeline-state-resolver/src/integrations/lawo/connection.ts, packages/timeline-state-resolver/src/integrations/lawo/diff.ts, packages/timeline-state-resolver/src/integrations/lawo/index.ts, packages/timeline-state-resolver/src/integrations/lawo/state.ts, packages/timeline-state-resolver/src/service/devices.ts
This pull request is posted on behalf of NRK.
This is a:  Refactor of the Lawo integration
No new behaviours expected
=> chore: refactor lawo integration

packages/timeline-state-resolver/src/integrations/vmix/vMixStateDiffer.ts, packages/timeline-state-resolver/src/integrations/vmix/vMixTimelineStateConverter.ts
This is a: 
Bug fix
vMix device integration throws an error when some resources are mapped "sparsely", e.g. Overlay 2 and 4 are mapped, but 1 and 3 are not.
Sparse arrays in the State are handled safely.
It can be tested with Sofie or QuickTSR. Create a mapping for Overlay 2, but not for Overlay 1. Create a timeline object for Overlay 2. Verify no errors are appearing in the logs and the timeline object is effective.
=> fix(vMix): handle sparse arrays in the state

packages/timeline-state-resolver/src/conductor.ts, packages/timeline-state-resolver/src/integrations/tricaster/__tests__/index.spec.ts, packages/timeline-state-resolver/src/integrations/tricaster/__tests__/tricasterStateDiffer.spec.ts, packages/timeline-state-resolver/src/integrations/tricaster/index.ts, packages/timeline-state-resolver/src/integrations/tricaster/triCasterCommands.ts, packages/timeline-state-resolver/src/integrations/tricaster/triCasterStateDiffer.ts, packages/timeline-state-resolver/src/service/devices.ts
=> feat: refactor tricaster device SOFIE-2497

packages/timeline-state-resolver/src/AsyncResolver.ts
This is a: 
Bug fix (?)
Initial timeline resolving trace is enabled
As per the existing code comment, initial timeline resolving trace is disabled
=> fix: disable initial timeline trace

packages/timeline-state-resolver/src/integrations/sisyfos/connection.ts
This pull request is posted on behalf of the BBC
This is a: 
Bug fix
If a `triggerValue` or the `SetSisyfosChannelState` action was used then the default values would be applied if there were no values in the state.
Values are only applied if present.
=> fix(sisyfos): Don't apply default values on set channel

packages/timeline-state-resolver-types/src/generated/atem.ts, packages/timeline-state-resolver/src/integrations/atem/$schemas/actions.json, packages/timeline-state-resolver/src/integrations/atem/index.ts
(This replaces PR https://github.com/Sofie-Automation/sofie-timeline-state-resolver/pull/391)
This is a: Feature
This PR adds a TSR Action for triggering an Atem Macro
=> feat: Add Atem Action: runMacro (R53)
