Sofie-Automation/sofie-timeline-state-resolver

- src/devices/__tests__/panasonicPTZ.spec.ts
- src/devices/panasonicPTZ.ts
- src/devices/panasonicPTZAPI.ts
Fix for an issue with formatting of the set zoom command to camera & also improves logging of the commands so that the actual URL requested is also logged.
The command is sent with the speed code sent as "FFFh", and should be sent as "FFF" (the Panasonic manual isn't very clear on what formatting should be used). Also, the logging from the Panasonic PTZ device is very sparse.
> Panasonic PTZ improvements

- src/devices/atem.ts
This changes the atem device to not use the originalLLayer property, and instead rely on core to insert lookahead onto the same layer. As the doesn't have a background that it can use to preload, doing it via a separate layer makes no sense (unlike with ccg)
Partner of https://github.com/nrkno/tv-automation-server-core/commit/f0df41ce2b81c8e4b2017ab7e2fef8ba523990fb
> feat(atem): Simplify lookahead handling logic to only support WHEN_CLEAR and the updated RETAIN mode

- src/conductor.ts
This restricts the next resolve time to inside the current window, to ensure we don't miss something that the timeline excluded.
If we have an active group at 1000-10000, and another group at 9000. After a resolve at 2000, the next resolve will be at 10000, so the start of the new group will be done late. 
> fix(tsr): Restrict the next resolve time to inside the current window

- src/devices/httpWatcher.ts
Fix
We auto-set URI if not defined to `http://localhost`. No lower bound on interval time.
Show a warning `status.BAD` in stead. 
Setting minimum interval to 1000 (1 second)
> fix: set minimum interval to 1 second + 'URI not set' warning

- examples/playVideoInCaspar.ts
- examples/testChangeTimelineQuickly.ts
- src/devices/__tests__/casparcg.spec.ts
- src/devices/casparCG.ts
- src/types/src/casparcg.ts
Replaces TimelineObjCCGVideo and TimelineObjCCGAudio with a single TimelineObjCCGMedia type.
Any objects of the old type will still work currently. As a second phase later on we can remove the TimelineContentTypeCasparCg enum values for them too.
> feat: Combine casparcg VIDEO and AUDIO types into single MEDIA type

- package.json
- src/__tests__/library.spec.ts
- src/index.ts
- src/types/package.json
- src/types/src/__tests__/library.spec.ts
- src/types/src/__tests__/osc.spec.ts
- src/types/src/osc.ts
There was an unexpected error in the previous publication of TSR causing the types-library to not be importable by library consumers.
This PR fixes the issue and adds unit tests to make sure the library stays importable.
> Fix: typings library

- src/devices/quantel.ts
This is a fix to mark all lookaheads as notOnAir
> fix: Quantel: set all lookahead objects as notOnAir

- src/devices/__tests__/lawo.spec.ts
- src/devices/lawo.ts
- src/types/src/lawo.ts
This PR removes the use of the triggerValue on the lawo timeline objects and instead looks for an object on the timeline with a triggerValue. This means that timings for retriggering can be more precise.
In addition, removing a triggerValue from the timeline will no longer retrigger commands as we consider retrigger to be an action and not a state.
> feat: use a timeline obj to retrigger lawo commands

- src/devices/atem.ts
Previous behaviour:
Audio channels would not be controlled by TSR at all
New behaviour:
Timeline objects are merged correctly into the state objects and TSR controls the audio channels on the atem
> fix(atem): audio channel tsr objects are correctly merged

- src/conductor.ts
I cant find anything in Kibana that was using the estimateResolveTime codepath.
Reading through this confirms that it could never be reached too (unless now was somehow 0). This should work the same, but factor in estimatedResolveTime
> fix: estimateResolveTime was unused due to avoiding any resolves for times in the past

- package.json
- src/devices/casparCG.ts
- src/types/src/casparcg.ts
- yarn.lock
Version 2.1.9 NRK of CasparCG will contain new parameters for audio fades during a sting transition. This PR adds support for a new parameter format and 2 new parameters.
The new format is `STING (MASK="[string]" OVERLAY="[string]" TRIGGER_POINT=[number] AUDIO_FADE_START=[number] AUDIO_FADE_DURATION=[number])`
The new parameters are `AUDIO_FADE_START` and `AUDIO_FADE_DURATION`
This PR is dependent on https://github.com/SuperFlyTV/casparcg-state/pull/37 and https://github.com/SuperFlyTV/casparcg-connection/pull/144
> Feature: CasparCG sting transition audio fades

- src/conductor.ts
It turns out that the callbacks aren't sent properly, as the state was cleared at a bad time.
This moves the whole check-for-callbacks functionality forwards in time, making the state (this._sentCallbacks) to be in sync with the time of sending.
> fix: bug fix in callbacks

- src/devices/quantelGateway.ts
This is a fix for an error that appears when having restarted the ISA, causing no ports to be created.
I'm merging this in fast-lane, as this causes a critical bug in prod.
> fix: Quantel 

- src/conductor.ts
We were never setting any value for `this._resolvedStates`, it was only ever being read and reset. This meant that for every point on the timeline where we needed a resolved timeline, we would be recalculating from scratch.
Additionally, we were record the concrete times for we predicted for 'now' pieces, so a second resolve would substitute a different time
But more crucially, this meant that if a timeline had multiple events close to each other, we would get different 'now' times for each of them. Which would result in the a flicker on the program output until the timeline stabilised with concrete times.
This is very visible by commenting out …
> fix: caching of resolved states not working

- package.json
- src/conductor.ts
- yarn.lock
When using Promise.all, it will reject when the first child rejects. The other children will keep executing until completion.
This will lead to race conditions as we run many of these operations behind a lock to ensure only one happens at a time.
By using p-all, we can tell it to reject only once they have all completed, and so we will retain the lock until they are all done.
> feat: use p-all instead of Promise.all for better handling when one rejects

- src/types/src/casparcg.ts
This is a small fix in the casparcg-typings.
I found out that we did have defined the enums for `ITransition.easing`, `ITransition.direction` & `ITransition.type`, but we didn't use them.
> fix: set interface to stricter typings

- src/types/src/atem.ts
- Re-enables the `programInput` property of the `me` object, allowing program to be cut directly. This in turn allows the preview source to be set.
- Adds documentation to the ATEM type definitions, including acceptable value ranges for numeric properties.
> ATEM interface documentation

- package.json
- src/__mocks__/v-connection.ts
- src/devices/__tests__/vizMSE.spec.ts
- src/devices/vizMSE.ts
- src/types/src/vizMSE.ts
- yarn.lock
Adds Viz clear commands. These are plain-text commands sent to clear and reset viz layers. They can be sent by setting the `Commands to send to clear graphics` setting in the Viz device and a timeline object like:
```
{
id: '',
enable: {
start: 1000,
duration: 1000
},
priority: 1,
layer: 'clear_layer',
content: {
deviceType: TSR.DeviceType.VIZMSE,
type: TSR.TimelineContentTypeVizMSE.CLEAR_ALL_ELEMENTS,
channelsToSendCommands: ['CHANNEL1', 'CHANNEL2']
}
}
```
> feat: Viz clear commands

- README.md
- package.json
- src/devices/__tests__/lawo.spec.ts
- src/devices/lawo.ts
- src/types/src/lawo.ts
- yarn.lock
This PR gives the timeline author the ability to define the fader value for multiple Lawo-sources in a single object
Similar to https://github.com/nrkno/tv-automation-state-timeline-resolver/pull/151
In addition it removes the `Fader/Motor dB Value` object in favour of a flat structure
Example timeline object for composites:
```ts
{
id: 'obj0',
enable: {
while: 1
},
layer: 'lawo_base',
content: {
deviceType: DeviceType.LAWO,
type: TimelineContentTypeLawo.SOURCES,
sources: [{
mappingName: 'lawo_c1_fader',
value: -6
},{
mappingName: 'lawo_c2_fader',
value: -6
}]
}
}
```
New timeline object content structure
```ts
{
deviceType: DeviceType.LAWO,
type: TimelineContentTypeLawo.SOURCE,
faderValue: -6,
transitionDuration: 750
}
```
> Feat: audio interface combined faders for Lawo

- package.json
- src/AsyncResolver.ts
- src/__tests__/conductor.spec.ts
- src/conductor.ts
- src/devices/__tests__/atem.spec.ts
- src/types/package.json
- src/types/src/superfly-timeline.ts
- src/types/yarn.lock
- yarn.lock
This PR updates the timeline dependency to the latest and adds a config option (`useCacheWhenResolving`) to use the new timeline-resolve feature for using a cache to do partial resolves (improves performance when only small changes are made in the timeline)
> Timeline upgrade + partial resolve

- src/devices/lawo.ts
The mc2 mixer series (unlike the power core series) does not carry the source identifier in the root of the channel, thus in order to be able to map a source to a fader we need to look into the tree to figure out the source identifier.
> Feat: lawo source identifier node

- src/devices/__tests__/casparcg.spec.ts
- src/devices/casparCG.ts
- src/types/src/casparcg.ts
This PR adds support to set the fps used in CasparCG State diffing mechanisms and time calculations.
> feat: set casparcg fps in device options

- package.json
- src/devices/__tests__/casparcg.spec.ts
- src/devices/casparCG.ts
- src/types/src/casparcg.ts
- yarn.lock
This PR introduces video and audio filters to the CasparCG implemenation for use with CasparCG 2.3.
_Note that this PR is a based on https://github.com/nrkno/tv-automation-state-timeline-resolver/pull/168, which has its own review process_
> Feat: casparcg ffmpeg filters

- src/devices/quantel.ts
A fix to warning messages logged when a Quantel port does not play. 
Logs `Quantel[object Object]` and `QuantelquantelRecovery: port didn't play` - sort of ugly and not useful.
Should now log `Quantel: { ... details }` and `Quantel: quantelRecovery: port didn't play`.
Turns out this was a symptom of a playout issue, not the cause. Having more information in this log will speed up future analysis.
> fix: better info and warnings for quantel issues

- src/types/src/atem.ts
This PR adds support for advanced SuperSource parameters in the `TimelineObjAtemSsrcProps` object.
These properties aren't typed in TSR, but TSR will forward them, if present in a Timeline Object.
The properties are specified on the interface. Associated properties are required when key flags are turned on. This enables backwards-compatibility when using `artPreMultiplied: true`, while enforcing the keying properties and border properties in when their respective flags are turned on.
> feat: add support for advanced settings in the TimelineObjAtemSsrcProps

- src/devices/__tests__/quantel.spec.ts
- src/devices/__tests__/quantelGatewayMock.ts
- src/devices/quantel.ts
A fix to quantel-specific behaviour of not resetting a clip when playing through a segment for the 2nd time after using setAsNext.
* Segment with a camera part followed by 2 (or more) Quantel VT parts. 
* Play camera, first VT, second VT ... set segment as next while playing 2nd VT. Take.
* Back on camera, then first VT plays OK. 2nd VT is either still playing or paused in preview. Take into 2nd VT and it is either still playing or paused on last frame.
Segment plays as expected.
> fix: don't set lockahead on a port that is playing

- package.json
- src/devices/__tests__/sisyfos.spec.ts
- src/devices/sisyfos.ts
- yarn.lock
Sisyfos retrigger mechanism was triggering commands for every channel exposed in Sisyfos, which meant that it touched channels that were not supposed to be automated at all. This PR changes the default state to only include channels that are in the Sofie mappings such that no commands will be sent for channels that are not mapped.
> fix(sisyfos): retrigger only channels that are mapped in Sofie

- src/devices/__tests__/quantel.spec.ts
- src/devices/__tests__/quantelGatewayMock.ts
- src/devices/quantel.ts
This PR adds a retry-logic for the Quantel device, to solve the issue when the Clip doesn't exist in the Quantel-verse at the time of loading of fragments.
> Fix: Quantel reload fragments if not found

- src/devices/__tests__/sisyfos.spec.ts
- src/devices/sisyfos.ts
- src/types/src/mapping.ts
- src/types/src/sisyfos.ts
Adds the `layerName` property to layer mappings, and utilises this in the Sisyfos integration as the default channel label.
No feature.
This PR adds an optional property to all mappings called `layerName`, which aims to serve two purposes.
First, this allows layer mappings to have a "friendly name" in core, something easier to recognise than the layer id used by blueprints.
Secondly, this PR adds a feature to the Sisyfos integration where, if the `layerName` is not blank, it will be used as the default label for a fader. This means that fader labels do not need to …
> feat: Mapping layer name

- src/devices/__tests__/quantel.spec.ts
- src/devices/quantel.ts
Big fix.
When a lookahead chantges on an off-air port, such as when cueing a BTS, the outTransition runs from one to the other.
Out transitions do not run between clips when the state is "notOnAir true" to "notOnAir" true.
Cueing BTSs appears to be delayed by 2 seconds (actually 1400ms plus load clip time) without this change.
> fix: don't run out transition when changing clip in preview

- packages/timeline-state-resolver-types/src/vizMSE.ts
- packages/timeline-state-resolver/src/devices/vizMSE.ts
- packages/timeline-state-resolver/src/expectedPlayoutItems.ts
Bug fixes and minor features in the VizMSE device
- `makeReady` waits for initializations, halting playlist activation for a couple seconds
- active<->rehearsal purges elements
- duplication of some elements occurs
fixes above, and:
- prevents from purging baseline expectedPlayoutItems
- improves logging
- reports Viz Engines that become unavailable
- attempts to reload elements after an Engine is restart
depends on https://github.com/olzzon/v-connection/pull/14 and https://github.com/olzzon/v-connection/pull/18
> fix: multiple VizMSE device fixes

- packages/timeline-state-resolver-types/src/httpSend.ts
- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/devices/__tests__/httpsend.spec.ts
- packages/timeline-state-resolver/src/devices/httpSend.ts
- yarn.lock
Resends failed HTTP commands as long as the object stays alive
Changes the deprecated request library to the got library
HTTP commands that fail are not retried, this can cause errors on air when DNS fails.
> feat: resend failing http commands

- packages/timeline-state-resolver/src/devices/device.ts
- packages/timeline-state-resolver/src/devices/obs.ts
- packages/timeline-state-resolver/src/devices/vmix.ts
- packages/timeline-state-resolver/src/doOnTime.ts
This PR adds some more emit events, that'll be used in Playout Gateway to log more filtered and detailed info about slow commands.
It is used in Playout Gateway in this PR: https://github.com/nrkno/tv-automation-server-core/pull/566
> feat: emit more detailed slowCommands

- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/devices/__tests__/quantel.spec.ts
- packages/timeline-state-resolver/src/devices/__tests__/quantelGatewayMock.ts
- packages/timeline-state-resolver/src/devices/quantel.ts
- yarn.lock
This PR fixes a potential bug in the Quantel device.
When renaming a port, there is sent `releasePort` and `getPort+createPort` in parallel, causing us to get errors from Quantel Gateway in the `createPort` function.
This PR makes TSR wait for any `releasePort` to finish (on that channel) before setting up a new port.
> fix: wait for releaseing quantel port before creating a new one

- packages/timeline-state-resolver-types/src/__tests__/library.spec.ts
- packages/timeline-state-resolver-types/src/atem.ts
Add missing type `TimelineObjAtemAudioChannel` to `TimelineObjAtemAny`
> fix: add missing atem-type to TimelineObjAtemAny

- packages/timeline-state-resolver/src/devices/vizMSE.ts
Feature
The Viz MSE request body is not included in the error message forwarded to the consuming library
The Viz MSE request body should now be included in the emitted commandError.
> feat(vizMSE): include request body when Viz MSE client error caught

- packages/timeline-state-resolver-types/src/abstract.ts
- packages/timeline-state-resolver-types/src/atem.ts
- packages/timeline-state-resolver-types/src/casparcg.ts
- packages/timeline-state-resolver-types/src/httpSend.ts
- packages/timeline-state-resolver-types/src/hyperdeck.ts
- packages/timeline-state-resolver-types/src/index.ts
- packages/timeline-state-resolver-types/src/lawo.ts
- packages/timeline-state-resolver-types/src/obs.ts
- packages/timeline-state-resolver-types/src/osc.ts
- packages/timeline-state-resolver-types/src/panasonicPTZ.ts
- packages/timeline-state-resolver-types/src/pharos.ts
- packages/timeline-state-resolver-types/src/quantel.ts
- packages/timeline-state-resolver-types/src/shotoku.ts
- packages/timeline-state-resolver-types/src/singularLive.ts
- packages/timeline-state-resolver-types/src/sisyfos.ts
- packages/timeline-state-resolver-types/src/tcpSend.ts
- packages/timeline-state-resolver-types/src/vizMSE.ts
- packages/timeline-state-resolver-types/src/vmix.ts
- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/lib.ts
This PR introduces a concept known as the _Timeline Datastore_. The datastore is a key value store that can be referenced from the content of a timeline object. When the timeline is resolved the references are replaced by the current value of the reference. If the timeline object started after the last update to the Timeline Datastore it may use a default value instead. 
Proposed API for timeline objects:
```ts
const mixEffect0: TSRTimelineObj = {
id: 'me0',
enable: {
start: Date.now(),
},
layer: 'me0',
content: {
deviceType: DeviceType.ATEM,
type: TimelineContentTypeAtem.MixEffect,
$references: {
input: { // the datastore key
path: 'me.input', // property to override
overwrite: false, // whether the default should override if the object is newer than the datastore value
}
},
me: {
input: …
```
> Feature: timeline datastore

- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/conductor.ts
- yarn.lock
Bug fix
The callBackId can sometimes be a unstable, resulting in multiple callbacks where there should only be one.
The callBackId uses originalStart falling back to start. Also, timeline state time is forwarded into `_diffStateForCallbacks`, instead of `getCurrentTime()`, since they can possibly be different.
> fix: stabilize timeline object callbacks by preferring originalStart in the callBackId

- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/devices/casparCG.ts
- yarn.lock
Bugfix
If a device is not initialized because the device thread crashed, or for some other reason the device fails to `terminate()` running _removeDevice will wait forever for it to do so.
This adds a timeout, so that the removal process can progress and the thread can be terminated.
> fix: timeout a device terminate operation if it takes too long and force-terminate

- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/devices/deviceContainer.ts
Bugfix
There is no `error` event handler registered on the device threads, meaning that if a device throws a thread-level error, nothing is there to catch it and log it.
Add an event handler to catch the errors. This should also improve the stability, because an uncaught error in the threadedClass could crash the entire playout gateway.
> fix: threaded class error handler

- packages/timeline-state-resolver/src/__mocks__/net.ts
- packages/timeline-state-resolver/src/__mocks__/v-connection.ts
- packages/timeline-state-resolver/src/devices/__tests__/vizMSE.spec.ts
- packages/timeline-state-resolver/src/devices/vizMSE.ts
* **What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fix, re-adding a feature missing since May 2nd.
* **What is the current behavior? (You can also link to an open issue here)**
If Clear-commands are specified, they will run on each rundown activation.
Clear-commands will only run (if specified) AND the option clearAllOnMakeRady is set to true.
* **Other information:**
Without this change, the option clearAllOnMakeReady is useless/not being used anywhere, and should be removed.
> fix: re-adds a check for clearAllOnMakeReady before doing so

- packages/timeline-state-resolver/src/integrations/vizMSE/index.ts
Add method to Viz device
-
This PR adds a method that can be manually called that purges all elements from the Viz Rundown
> Fix: Viz: purge rundown

- packages/timeline-state-resolver/src/integrations/casparCG/__tests__/casparcg.spec.ts
- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
**Bug report:** retries of loadbg commands even when the command was succesful
**Issue found:** CasparCG state storage uses fast-clone for it's state storage, this does not respect classes (they convert to objects) therefore the diff mechanism was triggered.
**Additional issues found:** A successful play command without parameters could stop the retry logic from further executing because the entire state of that layer would be copied into the tracked state
**Solutions:** 
- Move away from the casparcg-state provided state storage to an internal storage object. We do shallow copies but with careful modifications this should not cause any issues.
- Decision branch for whether copying the intended state into the tracked state is correct depending on the executed command
> Fix bug: casparcg retries

- packages/timeline-state-resolver-types/src/__tests__/__snapshots__/index.spec.ts.snap
- packages/timeline-state-resolver-types/src/httpSend.ts
- packages/timeline-state-resolver/src/__tests__/__snapshots__/index.spec.ts.snap
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
Bug fix
HTTPSend device didn't send GET requests at all
HTTPSend now sends GET requests.
User can also choose how the `body` is sent ("json" or "form" type) for POST/PUT/etc requests.
ref: https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#json
I've tested this to work, using quickTSR and a local http-server.
This should be backwards-compatible as it doesn't change the default way data is sent for POST/PUT/etc.
> Fix: http get requests

- .github/workflows/node.yaml
- packages/timeline-state-resolver-types/package.json
- packages/timeline-state-resolver/package.json
This PR adds support for Node v18 in CI and in "engines" in package.js.
Since it was such a small change, I thought that we could just add it right away.
FYI: I did the same in threadedclass, and[ it seems to work without a hitch](https://github.com/nytamin/threadedClass/actions/runs/3479117410), so that should be good too for v18.
> Add support for Node18

- packages/timeline-state-resolver-types/src/device.ts
- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/devices/device.ts
- packages/timeline-state-resolver/src/devices/deviceContainer.ts
- packages/timeline-state-resolver/src/integrations/abstract/index.ts
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds the ability for devices to emit debug information that reflects their internal state.
See [this PR against core](https://github.com/nrkno/sofie-core/pull/823) for full feature description.
**What is the current behavior?** (You can also link to an open issue here)
New feature.
**What is the new behavior (if this is a feature change)?**
- Adds events and settings for emitting debug state information.
- Adds the ability to emit debug state to the Abstract device, if the sub-device has state debugging enabled.
**Other information**:
This PR has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment.
> feat: Emit debug state information

- packages/timeline-state-resolver-types/src/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmix.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
This PR is being opened on behalf of TV 2 Norway.
Feature
vMix scripts cannot be started or stopped with TSR.
vMix scripts can be invoked and cancelled now:
```ts
export const input: TSRInput = {
timeline: [
literal<TSRTimelineObj<TimelineContentVMixScript>>({
id: 'script0',
enable: {
start: Date.now(),
duration: 20 * 1000,
},
layer: 'vmixLayer0',
content: {
deviceType: DeviceType.VMIX,
type: TimelineContentTypeVMix.SCRIPT,
name: 'myscript',
},
}),
],
}
```
Tested via quick-tsr by writing a short VB.NET script that just has two console …
> feat(vmix): add support for starting and stopping VB.NET scripts

- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
This PR is being opened on behalf of TV 2 Norway.
Bug fix
TSR fails to parse vMix TCP API responses which span multiple packets, due to a miscalculation of the response **body** length versus the response **header** length.
When checking to see if a response **body** has fully come in, the response **header** length is subtracted from the expected length of the body.
Debugged and confirmed using `quick-tsr `🙆‍♂️
> fix: properly parse multi-packet vMix TCP API responses

- packages/timeline-state-resolver-types/src/index.ts
In https://github.com/nrkno/sofie-timeline-state-resolver/pull/243, there was a conflict with both `MULTI_OSC` and `TRICASTER` wanting to have the id of `24`.
To minimise impact, `MULTI_OSC` has been changed to 25, and we should do the same in R49 (the first release containing `MULTI_OSC`) to avoid `MULTI_OSC: 24` ever reaching a production deployment
> fix: change `DeviceType.MULTI_OSC` value

- packages/timeline-state-resolver-types/src/generated/casparCG.ts
- packages/timeline-state-resolver/src/integrations/casparCG/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
Bug fix
Calling the `restart-caspar` action assumes that the launcher process ID is `casparcg` so will either fail or restart the wrong Caspar instance if this is not the case
The launcher process ID can now be specified.
> fix: Specify process ID for CasparCG restart - SOFIE-1646

- packages/timeline-state-resolver-types/src/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmix.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...
Feature
The input restart command is not supported in vMix.
An optional `restart` property has been added to vMix input timeline objects, to restart whatever media might be present there.
I wasn't sure if I should PR this to R50 or R49.
> feat: add restart command to vMix inputs

- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
bug fix
receiving a `404 LOADBG FAILED` followed by `202 LOAD OK` or `202 PLAY OK` would trick the state into thinking that the clip was loaded.
The state tracking has been reviewed, with the following changes:
* the `else` case has been removed, as that was catching these invalid PLAY commands
* LOAD commands are treated the same as PLAY
* the PLAY if statement, had incorrect brackets, causing it to catch all commands which didnt have a clip property
* Various undefined errors have been fixed, as `confirmedChannelState.layers[resCommand.layer]` can be undefined, so …
> fix: handle some additional cases in casparCG trackedState SOFIE-2359

- packages/timeline-state-resolver/src/integrations/singularLive/index.ts
Bug fix
Singular.live timeline objects do not work.
Singular.live timeline objects work.
This is how the Singular.live API expects them to be formatted. This got accidentally removed when migrating away from `request`.
> fix: wrap singular.live JSON commands in an array

- packages/timeline-state-resolver/src/integrations/panasonicPTZ/__tests__/panasonicPTZ.spec.ts
- packages/timeline-state-resolver/src/integrations/panasonicPTZ/index.ts
Refactor/bugfix
The Panasonic PTZ integration sets up an interval to poll for device state. This interval is not cleared anywhere.
The commands to the Panasonic PTZ device are not sent in any particular order.
A specific, predictable order is set for commands to be sent to the Panasonic device at the same time. Preset speed is sent first, then zoom speed, then zoom property, and then finally, preset memory recall.
The timeout is cleared on device termination.
This probably had no side-effects in production, but just was messy.
> fix(PanasonicPTZ): clear ping interval on terminate

- packages/timeline-state-resolver-types/src/generated/vmix.ts
- packages/timeline-state-resolver-types/src/vmix.ts
- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/integrations/vmix/$schemas/mappings.json
- packages/timeline-state-resolver/src/integrations/vmix/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmix.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
- packages/timeline-state-resolver/src/lib.ts
- yarn.lock
Feature
If TSR sends a media load command which fails due the file not being found, TSR will not retry loading that file.
TSR will retry loading media files that are not found until it succeeds.
I added some additional comments to the code to clarify things which confused me. I also tested everything via quickTSR.
> feat(vMix): retry sending media load commands if the file wasn't found

- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
Bug fix
Under certain conditions, such as when running in Docker, TSR can fail to stitch together multi-packet responses from vMix (such as the `XML` response), leading to the device never initializing and therefore not working.
Multi-packet responses are no longer joined together with an extra newline. I'm reasonably confident that we never want this newline, but perhaps I'm not seeing some scenario where the addition of a newline needs to be conditional.
I have no idea how this bug is different from #249, but it is. I don't know why that …
> fix: vmix: don't join response packets together with an extraneous newline

- packages/timeline-state-resolver-types/src/generated/httpSend.ts
- packages/timeline-state-resolver/src/integrations/httpSend/$schemas/actions.json
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
Bug fix
httpSend SendCommand TSR action has a separate less well typed payload (and is missing the headers property)
SendCommand payload now inherits from the normal httpSend TSR type
> fix(httpSend): Use the same types for the sendCommand action as a timeline object

- packages/timeline-state-resolver-types/src/generated/httpSend.ts
- packages/timeline-state-resolver-types/src/httpSend.ts
- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/__tests__/conductor.spec.ts
- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/integrations/httpSend/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/httpSend/__tests__/httpsend.spec.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- packages/timeline-state-resolver/src/service/devices.ts
- packages/timeline-state-resolver/src/service/remoteDeviceInstance.ts
- yarn.lock
No DNS cache
Requests are cached, respecting the TTL of the records.
Also updates the HTTP send device to the new format
> chore: convert http device & cache dns reqs

- packages/timeline-state-resolver-types/src/atem.ts
- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/integrations/atem/index.ts
- yarn.lock
feature
Allow for controlling the audio routing in the ATEM TVS HD8.  
Only the outpts with a mapping and timeline object on the layer will be controlled
This has not been tested against a compatible atem, but the network traffic has been looked at against a different model
> feat: atem audio routing control SOFIE-2512

- packages/timeline-state-resolver-types/src/generated/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmix.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmixAPI.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
Bug fix and feature, kind of.
Under common conditions, the existing system to retry loading missing media will add that media to List Inputs (aka playlists) exactly twice, resulting in bad behavior in playout.
This PR completely changes the mechanism used for this system. Instead of detecting failed commands, we instead poll the state of vMix and use that to determine how different the real state of vMix is from our expected state. This difference is then used to generate new commands, same as any other state update. …
> fix(vmix): fix scenario where the media load retry system would load clips into playlists twice

- packages/timeline-state-resolver/src/integrations/sisyfos/__tests__/sisyfos.spec.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/connection.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/index.ts
Feature (sisyfos)
Sisyfos cannot change fade time if the fader `isPgm` value isn't changed, so level changes cannot have adjustable fade time.
In conjunction with https://github.com/tv2/sisyfos-audio-controller/pull/271 the `fadeTime` property is sent with level changes.
Tested against an unmodified version of Sisyfos (4.18.0) and appears to have no ill effects so should be fine to be in TSR until the Sisyfos PR is merged.
> feat(sisyfos): Send fadeTime with faderLevel if specified

- packages/timeline-state-resolver-types/src/generated/httpSend.ts
- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/integrations/httpSend/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- yarn.lock
Feature
HTTP Requests that require a proxy fail
HTTP Requests that require a proxy succeed.
~~An optional global request timeout is introduced.~~ Removed because it's causing errors even when requests suceed
Reference implementation: https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying
> Proxy support for the HTTPSend device

- packages/timeline-state-resolver/src/integrations/vmix/index.ts
Chore or mild feature.
The vMix device does not offer state debugging.
This vMix device will now emit a new debug state on every timeline received.
None.
> chore(vmix): add state debugging

- packages/timeline-state-resolver/src/integrations/sofieChef/api.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/index.ts
Functionality fix
If Sofie Chef goes offline and then comes back, there will be no resync of state, so Chef will continue to display the default url.
Upon a reconnect, TSR resynct the state and sends new commands.
This PR depends on https://github.com/nrkno/sofie-chef/pull/6
> fix: resync chef on reconnect (SOFIE-2544)

- packages/timeline-state-resolver/src/integrations/atem/index.ts
- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- packages/timeline-state-resolver/src/integrations/osc/index.ts
- packages/timeline-state-resolver/src/integrations/shotoku/index.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/connection.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/index.ts
- packages/timeline-state-resolver/src/integrations/vizMSE/index.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
When a device is terminated it should be ready for garbage collection. A lot of devices don't seem to do this very well, this isn't a problem when ran in multi threaded mode because the thread can be restarted but in single threaded mode can cause issues.
In addition the sisyfos device used a fixed local port which is unnecessary and prevented us from running multiple connections (combined with the above this caused connection instability)
> Sisyfos device would not garbage collect (Sofie 2576)

- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
Bug fix
* Objects on CasparCG channel 1 were not being played.
* Objects on CasparCG channel 0 were being played on channel 1.
* TSR was stuck reloading some objects (I believe as a side effect of the two above issues).
It looks like a git merge went slightly wrong here. Some lines are duplicated, others are doing almost the same thing but slightly differently.
The block has been tidied to avoid duplication and avoid unnecessary work
I found this bug and wrote the fix against r51, I have not tested it in R50 but see no reason why it wouldnt …
> fix: bad merge in casparcg device, causing issues with channel 1

- packages/timeline-state-resolver-types/src/generated/casparCG.ts
- packages/timeline-state-resolver/examples/testChangeTimelineQuickly.ts
- packages/timeline-state-resolver/src/integrations/casparCG/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/casparCG/__tests__/casparcg.spec.ts
Fix
The option `useScheduling` for the casparcg device is not used in the code, as it appears to be no longer supported by casparcg-connection
Option is removed
> fix: remove unused casparcg useScheduling option

- packages/quick-tsr/src/tsrHandler.ts
Small improvements in QuickTSR (no production code changes for consumers of the actual library, so maybe it's more of a chore than a feat?)
Device status is logged as `[object Object]`. No debug and command logs when enabled for devices
Device status is stringified. Command report and debug logging work when enabled with `reportAllCommands: true` and `debug: true` respectively.
Opened towards release49, but I can change that if needed.
> feat: improve QuickTSR logging

- package.json
- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/__mocks__/got.ts
- packages/timeline-state-resolver/src/integrations/panasonicPTZ/__tests__/panasonicPTZ.spec.ts
- yarn.lock
Bug fix
* **What is the current behavior?**
There is a bug in v-connection that we've seen in prod: https://github.com/tv2/v-connection/pull/59
`PepTalk inexist error for request 755644: 755644 error inexist`
* **What is the new behavior?**
The error should (hopefully) not return
> fix: update v-connection dependency

- packages/timeline-state-resolver/src/integrations/__tests__/testlib.ts
- packages/timeline-state-resolver/src/integrations/atem/index.ts
- packages/timeline-state-resolver/src/service/DeviceInstance.ts
- packages/timeline-state-resolver/src/service/device.ts
- packages/timeline-state-resolver/src/service/devices.ts
This is a bug fix.
**Expected behaviour**
The atem integration will initiate correctly and enforce its state.
**Observed behaviour**
The atem integration does a state diff before it has connected to the actual device. This returns no commands. The State Handler than transitions to this state and expects it to be current.
Once the device is connected, a `resetResolver` is called. This does not reset the state itself causing it to diff against an incorrect current state and will again return no commands
**Proposed fix**
Add a method to update the current state in the State Handler on the context. In addition, chane the `resetState` context method to change the current state to `undefined`
> fix: reset atem upon connection

- packages/timeline-state-resolver-types/src/generated/quantel.ts
- packages/timeline-state-resolver/src/integrations/quantel/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/quantel/index.ts
This is a: fix / improvement
When the connection to the ISA is lost a connection error is immediately emitted.
When the connection to the ISA is lost the connection error will be suppressed momentarily. This allows it to fail over to a backup isa quietly.
> fix: suppress quantel disconnect shortly

- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixResponseStreamReader.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmixMock.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixResponseStreamReader.ts
This is a: 
Bug fix / Code improvement
It could happen that incomplete XML message would be attempted to be processed by the 'data' event handler, causing an error to be thrown. As a result the old, incomplete data got indefinitely stuck in the `_unprocessedLines` of the `BaseConnection`.
The logic for processing incoming data is extracted, refactored and covered by unit tests.
Handling of messages that may be fragmented over multiple TCP packets is fixed.
Errors thrown during the message handler are no longer interrupting the processing.
When reconnecting, previous and possibly incomplete data is discarded.
An assumption about the XML message being always terminated by a newline was made. This is not explicitly specified in the …
> fix(vMix): fragmented message handling SOFIE-2932

- packages/timeline-state-resolver-types/src/generated/atem.ts
- packages/timeline-state-resolver-types/src/integrations/atem.ts
- packages/timeline-state-resolver/src/integrations/atem/$schemas/mappings.json
- packages/timeline-state-resolver/src/integrations/atem/__tests__/__snapshots__/diffStates.spec.ts.snap
- packages/timeline-state-resolver/src/integrations/atem/__tests__/diffStates.spec.ts
- packages/timeline-state-resolver/src/integrations/atem/__tests__/stateBuilder.spec.ts
- packages/timeline-state-resolver/src/integrations/atem/diffState.ts
- packages/timeline-state-resolver/src/integrations/atem/index.ts
- packages/timeline-state-resolver/src/integrations/atem/stateBuilder.ts
This is a: Feature
It is now possible to control the color generators on a Blackmagic ATEM switcher.
This is only done for color generators where there is a mapping in Sofie.
> feat: atem color generator support SOFIE-2968

- packages/timeline-state-resolver-types/src/generated/vizMSE.ts
- packages/timeline-state-resolver/src/integrations/vizMSE/$schemas/actions.json
- packages/timeline-state-resolver/src/integrations/vizMSE/index.ts
This is a: Feature
Bug fix / Feature / Code improvement / Documentation improvement / Other (please specify)
An action trigger will perform a combination-macro of Clear Engine and Purge and Activation command for Viz
> viz reset action (Sofie 2830)

- packages/timeline-state-resolver/src/__mocks__/net.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixResponseStreamReader.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmixMock.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixResponseStreamReader.ts
This is a: 
Bug fix
An utf-8 character consisting of more than one byte appearing in a message received from vMix could make the message unprocessable, ~~or turn into a garbled character.~~
The vMixResponseStreamReader class now respects multi-byte characters in XML messages.
The assumptions about Socket's 'data' event providing a Buffer are corrected in code and in the tests. 
Details of the fix:
The data length that vMix provides is in bytes, previously incorrectly interpreted as length in characters.
~~The line remainder is now stored as a Buffer in case the arriving data is fragmented mid-character.~~
> fix(vMix): handling XML messages with multi-byte characters

- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/__tests__/diffStates.spec.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/__tests__/sofieChef.spec.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/diffStates.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/index.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/stateBuilder.ts
- packages/timeline-state-resolver/src/service/devices.ts
This is a: Code improvement
Refactors the Chef device to the new structure
> feat: refactor chef device

- packages/timeline-state-resolver-types/src/generated/httpSend.ts
- packages/timeline-state-resolver/package.json
- packages/timeline-state-resolver/src/integrations/httpSend/$schemas/options.json
- packages/timeline-state-resolver/src/integrations/httpSend/AuthenticatedHTTPSendDevice.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- packages/timeline-state-resolver/src/service/devices.ts
- yarn.lock
This PR is opened on behalf of TV 2 Norge,
This is a: 
Feature
Unless handled completely outside of the TSR, requests made through HTTPSend can't be authorized.
Two authorization methods are supported in the HTTPSend integration:
- OAuth 2.0 Client Credentials Flow: when configured, credentials are exchanged for a Bearer token that is added to EVERY outgoing request made through this instance of HTTPSend, and automatically refreshed.
- Long-lived Bearer token that is added to EVERY outgoing request. (probably not that common, but can be useful for testing purposes)
> feat(HTTPSend): Add OAuth 2.0 and Bearer Token options

- packages/timeline-state-resolver-types/src/integrations/pharos.ts
- packages/timeline-state-resolver/jest.config.js
- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/integrations/pharos/__tests__/pharos.spec.ts
- packages/timeline-state-resolver/src/integrations/pharos/diffStates.ts
- packages/timeline-state-resolver/src/integrations/pharos/index.ts
- packages/timeline-state-resolver/src/service/devices.ts
- scratch/ember-test.js
This is a: Code improvement
Refactors the Pharos device to the new structure
The new tests aren't the best quality, but it is a direct port of the existing tests
> feat: refactor pharos device SOFIE-2488

- packages/timeline-state-resolver-types/src/generated/httpSend.ts
- packages/timeline-state-resolver/src/integrations/httpSend/$schemas/actions.json
- packages/timeline-state-resolver/src/integrations/httpSend/AuthenticatedHTTPSendDevice.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
This PR is opened on behalf of TV 2 Norge.
This is a: 
Feature
SendCommand action of the HTTPSend device exists but does not provide any information about the received response.
If the request succeeds, SendCommand action provides a result including `statusCode`, `headers` and `body` of the response.
> feat(HTTPSend): return response data from HTTP SendCommand action

- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/integrations/singularLive/__tests__/singularLive.spec.ts
- packages/timeline-state-resolver/src/integrations/singularLive/index.ts
- packages/timeline-state-resolver/src/service/devices.ts
This is a: Code improvement 
Refactors the Telemetrics device to the new structure
> feat: refactor singular-live device SOFIE-2492

- packages/timeline-state-resolver/src/integrations/sisyfos/connection.ts
This is a: **Bug fix** 
TSR will not send the fadeTime parameter for PGM changes when the change comes from a `triggerValue` change
TSR send the fadeTime paramter for PGM changes during a channel reset
> fix: sisyfos add fade time during reset

- packages/timeline-state-resolver/src/integrations/atem/index.ts
This is a: Bug fix 
Trying to set the atem supersource border properties has no effect
> fix: atem supersource border properties SOFIE-3307

- packages/timeline-state-resolver-types/src/index.ts
- packages/timeline-state-resolver-types/src/integrations/casparcg.ts
- packages/timeline-state-resolver-types/src/integrations/httpSend.ts
- packages/timeline-state-resolver-types/src/integrations/sofieChef.ts
- packages/timeline-state-resolver/src/__tests__/lib.spec.ts
- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/stateBuilder.ts
- packages/timeline-state-resolver/src/lib.ts
This is a Feature
This allows for defining the urls for the httpsend device, as well as urls passed to the renderers in sofieChef and casparcg, in a format that allows for taking fragments from the datastore.
For example an object could look something like:
```
{
deviceType: 'httpSend',
type: 'post',
url: {
key: `http://example.com/{{subPath}?apiKey={{apiKey}}`,
args: {
subPath: 'my-default', // Overriden by the datastore
apiKey: '', // Taken from datastore
}
},
$references: {
'url.args.subPath': {
datastoreKey: 'httpSubpath',
overwrite: true,
},
'url.args.apiKey': {
datastoreKey: 'httpApiKey',
overwrite: false,
}
}
}
```
In this example, the 'apiKey' will be taken from the datastore, avoiding being baked into the rundown.
And the …
> feat: http url interpolation SOFIE-3310

- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/integrations/multiOsc/__tests__/multiOsc.spec.ts
- packages/timeline-state-resolver/src/integrations/multiOsc/index.ts
- packages/timeline-state-resolver/src/integrations/osc/index.ts
- packages/timeline-state-resolver/src/service/devices.ts
This is a: Code improvement 
Refactors the MultiOSC device into the new state handler flow
> chore: refactor multi-osc device to state handler flow SOFIE-2485

- packages/timeline-state-resolver/src/integrations/quantel/connection.ts
- packages/timeline-state-resolver/src/integrations/vizMSE/vizMSEManager.ts
- packages/timeline-state-resolver/src/waitGroup.ts
This is a: Bug fix 
viz and quantel use a similar flow of waiting and being able to satisfy those waits.
queued callbacks were never being cleared once called, resulting in them being gradually leaked
this has been refactored to share a common implementation, with the new implementation cleaning up the callbacks as they are called.
> fix: viz and quantel callback leak

- packages/timeline-state-resolver/src/__tests__/conductor.spec.ts
- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/service/devices.ts
An integration is given access to all the mappings and has to manually filter for device type and device id. This means that unless the developer filters for the device id, the mappings may be targeted at a different device.
Mappings are filtered for the device id before passing them to the integration.
Perhaps in the future we should also try to filter out mappings that have the wrong type
~~This is awaiting some testing in a production environment~~ This has been tested in a production environment
> Filter mappings such that an integration only sees its own mappings

- packages/timeline-state-resolver-types/src/index.ts
- packages/timeline-state-resolver/src/integrations/httpSend/__tests__/httpsend.spec.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- packages/timeline-state-resolver/src/integrations/quantel/connection.ts
- packages/timeline-state-resolver/src/service/commandExecutor.ts
- packages/timeline-state-resolver/src/service/device.ts
This is a: 
Bug fix
All commands in an HTTPSend device are sent sequentially, ignoring the `queueId` property.
HTTPSend device again supports the queueId property to allow separate sequential request queues.
* Ensure that HTTP integration still works as expected
* See if multiple parallel HTTP request can be made when using the queueId
> fix(HTTPSend): Allow HTTPSend commands to be sent in separate sequential queues (SOFIE-3431)

- packages/timeline-state-resolver-types/src/integrations/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/connection.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixStateDiffer.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixTimelineStateConverter.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixCommands.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixStateDiffer.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixTimelineStateConverter.ts
This is a: 
Feature
URL of the Browser input in vMix can not be controlled by TSR
URL of the Browser input in vMix can be controlled using the added `url` property of `TimelineContentVMixInput`.
There is a limitation: The URL can't be read via the API, therefore (re)start or reconnection may issue a BrowserNavigate command even if the URL is already as expected
1. Add a Browser input to vMix
2. Create a mapping and a timeline object as shown in the `'supports url'` test case
3. Verify if the URL has changed when the timeline object started
> feat(vMix): support browser source url in vMix

- packages/timeline-state-resolver-types/src/integrations/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/connection.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixStateDiffer.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixTimelineStateConverter.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixCommands.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixStateDiffer.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixTimelineStateConverter.ts
This is a: 
Feature 
_Index_ of inputs of types Photos, List and Virtual Set cannot be controlled by TSR.
_Index_ of inputs of types: 
- Photos, List (Selects the item in the list)
- Virtual Set (Zooms to selected preset using the current speed settings)
...can be controlled by the added `index` property of `TimelineContentVMixInput`, resulting in issuing the `SelectIndex` command.
The index starts from 1, which is not how indexes should work, but I'm following vMix's convention here.
1. Add an input of one of the three mentioned types, with more than one item(preset)
2. Create a mapping and a timeline object as shown in the `'supports index'` test case
3. Verify that the index changes when the timeline object starts
> feat(vMix): support index (list, photo, virtual set) in vMix

- yarn.lock
To fix a build error ("spawn EINVAL")
This pull request is posted on behalf of the NRK
This is a: Bug fix
Using Node.js 18.20.4 on Windows, installing dependencies (`yarn install`) fails  due to:
```
utf-8-validate@npm:6.0.4 couldn't be built successfully (exit code 1)
[...]
Error: spawn EINVAL
at ChildProcess.spawn (node:internal/child_process:414:11)
at Object.spawn (node:child_process:761:9)
at build (tsr\node_modules\node-gyp-build\bin.js:29:8)
```
This is due to a security patch released to all Node.js versions: https://github.com/nodejs/node/issues/52554#issuecomment-2061405161
Installation works.
> Fix build error spawn einval

- packages/timeline-state-resolver-types/src/generated/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/$schemas/actions.json
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
This is a: 
Feature
No TSR actions to start/stop External output in vMix
TSR actions to start/stop External output in vMix are added.
Note: Those actions are not taking the _External_ mapping and timeline objects into consideration. To avoid undefined behavior, either use the timeline or the actions to control the External output, not both.
When used with Sofie, it can be tested using the autogenerated buttons in the Playout Gateway section of Sofie settings.
Press _Start External_ and verify if the _External_ indicator lit up red in vMix.
Press _Stop External_ and verify if the _External_ indicator went back to grey in vMix.
> feat(EAV-423): add actions to start and stop External in vMix

- packages/timeline-state-resolver-types/src/integrations/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/connection.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixStateDiffer.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixTimelineStateConverter.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixXmlStateParser.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixCommands.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixStateDiffer.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixTimelineStateConverter.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixXmlStateParser.ts
This is a: 
Feature 
Text fields in Title inputs in vMix cannot be controlled by TSR.
Text fields in Title inputs in vMix can be controlled, using the newly added `text` property of `TimelineContentVMixInput`. They can only be addressed by the field name (a.k.a selected name), not by the index.
1. Add a Title input
2. Create a mapping and a timeline object similar to those in the `'supports text'` test case, using field names existing in the selected title template
3. Verify that the values for specified field names change when the timeline object starts
> feat(vMix): support setting text in vMix titles

- packages/timeline-state-resolver/src/integrations/sisyfos/__tests__/sisyfos.spec.ts
This pull request is posted on behalf of TV 2 Norge.
This is a: 
Other - increasing test coverage
Sisyfos per-channel `triggerValue` works correctly, but it isn't covered by tests
Added two test cases asserting that the feature works in two scenarios:
- when the value changes from one to another, and back
- when the value changes from `undefined` to defined, and back
> chore: add test cases for Sisyfos per-channel `triggerValue`

- packages/timeline-state-resolver-types/src/integrations/atem.ts
- packages/timeline-state-resolver/src/integrations/atem/__tests__/__snapshots__/diffStates.spec.ts.snap
- packages/timeline-state-resolver/src/integrations/atem/diffState.ts
This pull request is posted on behalf of the BBC.
Properties for the Stinger transition are exposed through tsr-types and the tsr atem integration diffs the properties as appropriate.
> feat(atem): add stinger support

- packages/timeline-state-resolver-types/src/generated/sisyfos.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/$schemas/actions.json
- packages/timeline-state-resolver/src/integrations/sisyfos/connection.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/index.ts
This is a: 
Feature 
No way to load a mixer preset using TSR.
TSR action is added, that allows to load a specified mixer preset.
~~It's a draft, because complementary changes haven't been yet contributed upstream in Sisyfos~~
Complementary changes in Sisyfos: https://github.com/olzzon/sisyfos-audio-controller/pull/8/commits/858d237c08523ada2589d62741f1fc95cf4626c0
> feat(Sisyfos): add sisyfos action to load mixer preset

- packages/timeline-state-resolver-types/src/integrations/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixStateDiffer.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixTimelineStateConverter.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixXmlStateParser.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixCommands.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixStateDiffer.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixTimelineStateConverter.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixXmlStateParser.ts
This is a: 
Feature
Image fields in Title inputs in vMix cannot be controlled by TSR.
Image fields in Title inputs in vMix can be controlled, using the newly added `images` property of TimelineContentVMixInput. They can only be addressed by the field name (a.k.a selected name), not by the index.
1. Add a Title input that contains a dynamic image field
2. Create a mapping and a timeline object similar to those in the `'supports images (titles)'` test case, using field name(s) existing in the selected title template
3. Verify that the images for specified field name(s) change when the timeline object starts
> feat(EAV-464): add images support for GT titles in vMix

- packages/timeline-state-resolver-types/src/__tests__/__snapshots__/index.spec.ts.snap
- packages/timeline-state-resolver-types/src/__tests__/templateString.spec.ts
- packages/timeline-state-resolver-types/src/index.ts
- packages/timeline-state-resolver-types/src/templateString.ts
- packages/timeline-state-resolver/src/__tests__/__snapshots__/index.spec.ts.snap
- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/stateBuilder.ts
- packages/timeline-state-resolver/src/lib.ts
This is a: Code improvement 
`TemplateString` is exported in TSR-types, and used in TSR-types data. But helper functions (such as `interpolateTemplateString`) that are essential to working with it, is not.
The helper functions `interpolateTemplateString` and `interpolateTemplateStringIfNeeded` are moved to TSR-types and now exported.
This is useful for consumers of TSR-types to be able to work with TSR-types data (for example `url: string | TemplateString`) without having to import TSR.
> fix: move functions related to TemplateString to TSR-types.

- packages/timeline-state-resolver-types/src/generated/vmix.ts
- packages/timeline-state-resolver-types/src/integrations/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/$schemas/mappings.json
- packages/timeline-state-resolver/src/integrations/vmix/README.md
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/mockState.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixStateDiffer.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixTimelineStateConverter.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vMixXmlStateParser.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmixMock.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixCommands.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixStateDiffer.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixTimelineStateConverter.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixXmlStateParser.ts
This is a: 
Feature
Not possible to control vMix audio buses themselves (except of routing inputs to them).
Support for vMix audio buses (Master, and A through G) is added. Only `mute` and `volume` are supported in this PR.
> feat: add basic support for vMix audio buses

- packages/timeline-state-resolver-types/src/generated/sisyfos.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/$schemas/mappings.json
- packages/timeline-state-resolver/src/integrations/sisyfos/__tests__/sisyfos.spec.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/connection.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/index.ts
This is a: 
Feature 
Sisyfos integration enforces certain default values for mapped channels, even if no timeline objects are present on the timeline, or if the timeline objects have certain values omited. It is, however, a requirement for us to leave the fader level, gain and input selector where the user set it through the GUI of Sisyfos, and never change nor reset them from the automation, but still have the automation control PGM and MUTE.
A new, optional, and backwards compatible option called `disableDefaults` is introduced to Sisyfos layer mappings. In the UI it is titled "Do not apply default state for this layer". When set to `true` on a particular mapping, no defaults will be applied for the mapped channel(s). Only values …
> feat(sisyfos): add `disableDefaults` option to sisyfos mappings

- packages/timeline-state-resolver/package.json
- yarn.lock
This is a: Bug fix 
There is a bug related to lookaheads, see https://github.com/nrkno/sofie-core/issues/1395
Updating superfly-timeline to 9.0.3 seems to solve the issue
> Update timeline dep, to fix a bug related to lookaheads

- packages/timeline-state-resolver/src/devices/device.ts
- packages/timeline-state-resolver/src/integrations/abstract/index.ts
- packages/timeline-state-resolver/src/integrations/atem/index.ts
- packages/timeline-state-resolver/src/integrations/casparCG/index.ts
- packages/timeline-state-resolver/src/integrations/httpSend/index.ts
- packages/timeline-state-resolver/src/integrations/httpWatcher/index.ts
- packages/timeline-state-resolver/src/integrations/hyperdeck/diffState.ts
- packages/timeline-state-resolver/src/integrations/hyperdeck/index.ts
- packages/timeline-state-resolver/src/integrations/lawo/diff.ts
- packages/timeline-state-resolver/src/integrations/multiOsc/index.ts
- packages/timeline-state-resolver/src/integrations/osc/index.ts
- packages/timeline-state-resolver/src/integrations/panasonicPTZ/diff.ts
- packages/timeline-state-resolver/src/integrations/pharos/index.ts
- packages/timeline-state-resolver/src/integrations/quantel/index.ts
- packages/timeline-state-resolver/src/integrations/shotoku/index.ts
- packages/timeline-state-resolver/src/integrations/singularLive/index.ts
- packages/timeline-state-resolver/src/integrations/sisyfos/index.ts
- packages/timeline-state-resolver/src/integrations/sofieChef/index.ts
- packages/timeline-state-resolver/src/integrations/tcpSend/index.ts
- packages/timeline-state-resolver/src/integrations/telemetrics/index.ts
- packages/timeline-state-resolver/src/integrations/tricaster/triCasterCommands.ts
- packages/timeline-state-resolver/src/integrations/viscaOverIP/index.ts
- packages/timeline-state-resolver/src/integrations/vizMSE/index.ts
- packages/timeline-state-resolver/src/integrations/vmix/index.ts
- packages/timeline-state-resolver/src/integrations/websocketClient/index.ts
- packages/timeline-state-resolver/src/service/DeviceInstance.ts
- packages/timeline-state-resolver/src/service/commandExecutor.ts
- packages/timeline-state-resolver/src/service/device.ts
- packages/timeline-state-resolver/src/service/stateHandler.ts
This pull request is posted on behalf of Superfly
This is a: Code improvement 
This makes a small improvement to type safety within the device integrations. Each device is using `CommandWithContext` and is expected to extend the type and override the `command` and `context` fields with concrete types.   
Instead, this PR changes this type to be a generic, which forces the connection to define these with a type alias instead.
At various points in the TSR internals this has to be done with `CommandWithContext<any, any>`, where it doesn't matter what the concrete types are. This is typically needed, and matches prior behaviour where the fields were typed as any inside CommandWithContext.
> chore: change CommandContext to be a generic instead of using fields typed as any

- packages/timeline-state-resolver/src/__tests__/lib.ts
- packages/timeline-state-resolver/src/__tests__/mockDeviceInstanceWrapper.ts
- packages/timeline-state-resolver/src/conductor.ts
- packages/timeline-state-resolver/src/integrations/abstract/index.ts
- packages/timeline-state-resolver/src/service/ConnectionManager.ts
- packages/timeline-state-resolver/src/service/DeviceInstance.ts
- packages/timeline-state-resolver/src/service/remoteDeviceInstance.ts
This is a: Code improvement
This removes the remaining usages of `DeviceOptionsAnyInternal`, replacing them with `DeviceOptionsAny`.
The types that make up `DeviceOptionsAnyInternal` are internal types that provide some additional option properties over the types in `DeviceOptionsAny`. These are used solely to expose some additional hooks for unit tests, so exposing these types in the public api is a little weird.
Instead we can assume the unit tests will use the appropriate types and that things will line up fine. It is also worth noting that this is exclusively used by integrations that have not been updated to the service flow, so defining these internal types should no longer happen for new integrations.
Additionally, this further …
> fix: remove DeviceOptionsAnyInternal type from public api

- packages/timeline-state-resolver/package.json
- yarn.lock
This is a: Bug fix
In certain scenarios, the resolving of a timeline crashes with an `Internal Error: There is already an object on layer`
as reported in https://github.com/SuperFlyTV/supertimeline/pull/109
Resolving does not crash
> Fix: Update timeline dependency to latest

- README.md
- packages/timeline-state-resolver-types/src/generated/vmix.ts
- packages/timeline-state-resolver-types/src/integrations/vmix.ts
- packages/timeline-state-resolver/src/integrations/vmix/$schemas/mappings.json
- packages/timeline-state-resolver/src/integrations/vmix/__tests__/vmix.spec.ts
- packages/timeline-state-resolver/src/integrations/vmix/connection.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixCommands.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixStateDiffer.ts
- packages/timeline-state-resolver/src/integrations/vmix/vMixTimelineStateConverter.ts
This pull request is posted on behalf of the BBC.
This is a: Bug fix / Feature
VMix cuts on Mixes are always done by using a Transition Command. This will replace the current on-air input with the new input and move the old input to the preview bus. 
VMix cuts on Mixes are done through the Active Input Command. This will replace the current on-air input with the new input but does _not_ change the preview bus. This is similar to how the Atem integration behaves when changing the "programInput" and instead of the "input" field.
_Note: in theory today it is possible to enable an overlay on the preview input and that would be enabled by the Transition Command but will not be enabled by the newly added Active Input Command. In reality, we never supported enabling overlays in preview anyway, …
> Add VMix Active Input Command
